"use client";
import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import {IndexedCodeSearch,LocalStorageTicketRepository,NavigationState,TicketQueryService,emptyCriteria,isVisible} from "../lib/navigation";
import type {Ticket,TicketEvent as Event,QueryCriteria} from "../lib/navigation";
import {runBenchmark,reportCSV} from "../lib/benchmark";
import type {BenchmarkReport} from "../lib/benchmark";

const now="30/08/2026, 6:00 p. m.";
const seed:Ticket[]=[
{id:1,code:"SB-DEMO-001",title:"Bloqueo de usuario en portal interno",description:"Un usuario de demostración no puede acceder al portal desde el inicio de su turno.",category:"Acceso",priority:"Alta",status:"En progreso",requester:"Usuario Demo 01",assignee:"Técnico Demo A",createdAt:now,events:[{id:1,type:"Creación",detail:"Solicitud demostrativa registrada con prioridad Alta",actor:"Usuario Demo 01",date:now},{id:2,type:"Asignación",detail:"Responsable asignado: Técnico Demo A",actor:"Agente de mesa",date:now}],comments:[]},
{id:2,code:"SB-DEMO-002",title:"Falla de impresión en oficina",description:"Una impresora del entorno de pruebas no responde y presenta documentos en cola.",category:"Hardware",priority:"Media",status:"Abierto",requester:"Usuario Demo 02",assignee:null,createdAt:now,events:[{id:1,type:"Creación",detail:"Solicitud demostrativa registrada con prioridad Media",actor:"Usuario Demo 02",date:now}],comments:[]},
{id:3,code:"SB-DEMO-003",title:"Actualización de cliente VPN",description:"Caso académico para actualizar el cliente seguro en equipos de demostración.",category:"Software",priority:"Baja",status:"Resuelto",requester:"Usuario Demo 03",assignee:"Técnico Demo B",createdAt:now,events:[{id:1,type:"Creación",detail:"Solicitud demostrativa registrada con prioridad Baja",actor:"Usuario Demo 03",date:now},{id:2,type:"Estado",detail:"Estado actualizado a Resuelto",actor:"Técnico Demo B",date:now}],comments:[{id:1,text:"Actualización de demostración completada y validada.",author:"Técnico Demo B",date:now}]},
{id:4,code:"SB-DEMO-004",title:"Intermitencia de red en sede de prueba",description:"Caso ficticio de pérdida de conectividad reportada en un entorno de demostración.",category:"Red",priority:"Crítica",status:"Cerrado",requester:"Usuario Demo 04",assignee:"Técnico Demo C",createdAt:now,events:[{id:1,type:"Creación",detail:"Solicitud demostrativa registrada con prioridad Crítica",actor:"Usuario Demo 04",date:now},{id:2,type:"Estado",detail:"Estado actualizado a Cerrado",actor:"Técnico Demo C",date:now}],comments:[]}
];
const technicians=["Técnico Demo A","Técnico Demo B","Técnico Demo C","Técnico Demo D"];
const statuses=["Abierto","En progreso","Resuelto","Cerrado"];
const stamp=()=>new Date().toLocaleString("es-CO");
const event=(type:string,detail:string,actor:string):Event=>({id:Date.now()+Math.random(),type,detail,actor,date:stamp()});

export default function Home(){
 const [tickets,setTickets]=useState<readonly Ticket[]>([]),[view,setView]=useState("Resumen"),[role,setRole]=useState("Agente"),[notice,setNotice]=useState(""),[error,setError]=useState(""),[selectedId,setSelectedId]=useState<number|null>(null);
 const [criteria,setCriteria]=useState<QueryCriteria>(emptyCriteria),[ready,setReady]=useState(false),[benchmark,setBenchmark]=useState<BenchmarkReport|null>(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState("");
 const serviceRef=useRef<TicketQueryService|null>(null),repoRef=useRef<LocalStorageTicketRepository|null>(null),navigation=useRef(new NavigationState()),detailRef=useRef<HTMLElement|null>(null),openerRef=useRef<HTMLElement|null>(null);
 const context=useMemo(()=>({role,userId:role==="Colaborador"?"Usuario Demo 01":role==="Técnico"?"Técnico Demo A":`${role} demo`}),[role]);
 useEffect(()=>{try{const repository=new LocalStorageTicketRepository(localStorage,seed);repoRef.current=repository;serviceRef.current=new TicketQueryService(repository,new IndexedCodeSearch());setTickets(repository.readAll());setReady(true)}catch(err){setError(errorMessage(err))}},[]);
 function errorMessage(err:unknown){return err instanceof Error?err.message:"No fue posible completar la operación."}
 function synchronize(){if(repoRef.current)setTickets(repoRef.current.readAll())}
 const result=useMemo(()=>serviceRef.current?serviceRef.current.query(criteria,context):{items:[],total:0,page:1,pageCount:0},[criteria,context,tickets]);
 useEffect(()=>{if(result.page!==criteria.page)setCriteria(current=>({...current,page:result.page}))},[result.page,criteria.page]);
 function setSearch(patch:Partial<QueryCriteria>){setCriteria(current=>({...current,...patch,page:1}))}
 function switchRole(next:string){setRole(next);setSelectedId(null);navigation.current.reset();setCriteria(emptyCriteria());setNotice("");setError("")}
 function openDetail(id:number){openerRef.current=document.activeElement as HTMLElement;navigation.current.save({...criteria,page:result.page},context);setSelectedId(id)}
 function closeDetail(){setSelectedId(null);setCriteria(navigation.current.restore(context));requestAnimationFrame(()=>openerRef.current?.focus())}
 useEffect(()=>{if(selectedId!==null)detailRef.current?.querySelector<HTMLButtonElement>('.close')?.focus()},[selectedId]);
 const visible=tickets.filter(ticket=>isVisible(ticket,context));
 const selected=visible.find(t=>t.id===selectedId)||null;
 const counts=[visible.filter(t=>["Abierto","En progreso"].includes(t.status)).length,visible.filter(t=>t.priority==="Crítica"&&t.status!=="Cerrado").length,visible.filter(t=>["Resuelto","Cerrado"].includes(t.status)).length];
 const actor=`Usuario demo (${role})`;
 function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!serviceRef.current||role==="Técnico")return;const f=e.currentTarget,d=new FormData(f),impact=Number(d.get("impact")),urgency=Number(d.get("urgency")),score=impact+urgency,priority=score>=6?"Crítica":score>=5?"Alta":score>=3?"Media":"Baja",id=Math.max(Date.now(),...tickets.map(t=>t.id+1));const t:Ticket={id,code:`SB-${id}`,title:String(d.get("title")).trim(),description:String(d.get("description")).trim(),category:String(d.get("category")),priority,status:"Abierto",requester:role==="Colaborador"?context.userId:String(d.get("requester")).trim(),assignee:null,createdAt:new Date().toISOString(),events:[event("Creación",`Solicitud registrada con prioridad ${priority}`,actor)],comments:[]};try{serviceRef.current.create(t);synchronize();f.reset();setCriteria(emptyCriteria());setError("");setNotice("Solicitud creada correctamente.");setView("Solicitudes")}catch(err){setError(errorMessage(err))}}
 function updateTicket(id:number,mutate:(t:Ticket)=>Ticket){const ticket=tickets.find(t=>t.id===id);if(!ticket||!serviceRef.current)return;try{serviceRef.current.update(ticket.code,mutate(ticket));synchronize();setError("")}catch(err){setError(errorMessage(err))}}
 function changeStatus(t:Ticket,status:string){if(role==="Colaborador")return;updateTicket(t.id,x=>({...x,status,events:[...x.events,event("Estado",`Estado actualizado de ${x.status} a ${status}`,actor)]}))}
 function assign(t:Ticket,assignee:string){if(!["Agente","Administrador"].includes(role))return;updateTicket(t.id,x=>({...x,assignee,events:[...x.events,event("Asignación",`Responsable asignado: ${assignee}`,actor)]}))}
 function addComment(e:FormEvent<HTMLFormElement>,t:Ticket){e.preventDefault();const f=e.currentTarget,text=String(new FormData(f).get("comment")).trim();if(!text)return;updateTicket(t.id,x=>({...x,comments:[...x.comments,{id:Date.now(),text,author:actor,date:stamp()}],events:[...x.events,event("Comentario","Se agregó una observación de seguimiento",actor)]}));f.reset()}
 async function evaluate(){setBusy(true);setError("");try{setBenchmark(await runBenchmark(navigator.userAgent,setProgress));setProgress("Evaluación completada. Los datos de la mesa de servicio se conservaron.")}catch(err){setError(errorMessage(err))}finally{setBusy(false)}}
 function download(name:string,text:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const nav=role==="Técnico"?["Resumen","Solicitudes","Evaluación"]:["Resumen","Solicitudes","Nueva solicitud","Evaluación"];
 return <><header><div className="top"><div className="brand"><div className="logo">SB</div><div><h1>ServiceBank</h1><p>Mesa de servicio tecnológica</p></div></div><span className="academic">Actividad 6 · Adriana Ramirez Bernal</span><select aria-label="Perfil activo" className="role" value={role} onChange={e=>{switchRole(e.target.value);setView("Solicitudes")}}>{["Colaborador","Agente","Técnico","Administrador"].map(x=><option key={x}>{x}</option>)}</select></div></header>
 <div className="layout"><aside><p className="navtitle">NAVEGACIÓN</p>{nav.map(x=><button className={"nav "+(view===x?"active":"")} key={x} onClick={()=>{setView(x);setNotice("");setSelectedId(null)}}>{x}</button>)}<div className="safe"><strong>Entorno de demostración</strong><br/>No contiene información real de Itaú ni autentica usuarios bancarios.</div></aside>
 <main className="content"><div className="eyebrow">OPERACIÓN TI</div><h2>{view}</h2><div className="sub">Vista activa como {role} ({context.userId}). {role==="Colaborador"?"Puedes registrar y consultar tus solicitudes.":role==="Técnico"?"Puedes consultar y actualizar tus solicitudes asignadas.":"Puedes asignar responsables y gestionar el ciclo de atención."}</div>{notice&&<div className="notice" role="status">{notice}</div>}{error&&<div className="error" role="alert">{error}{!ready&&<p>Los datos guardados se conservaron. Revisa el almacenamiento antes de volver a cargar.</p>}</div>}{!ready&&!error&&<p role="status">Cargando solicitudes…</p>}
 {ready&&view==="Resumen"&&<><div className="cards">{[["Solicitudes activas",counts[0]],["Prioridad crítica",counts[1]],["Resueltas",counts[2]]].map(x=><section className="card" key={x[0]}><div className="sub">{x[0]}</div><div className="metric">{x[1]}</div></section>)}</div><section className="card section"><h3>Actividad reciente</h3><TicketTable rows={[...visible].sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)).slice(0,5)} role={role} open={openDetail}/></section></>}
 {ready&&view==="Solicitudes"&&<section className="card"><h3>Listado de solicitudes</h3><div className="filters">
 <label className="field">Código exacto<input value={criteria.exactCode} onChange={e=>setSearch({exactCode:e.target.value})} placeholder="Ej. SB-DEMO-001"/></label>
 <label className="field">Buscar por asunto<input value={criteria.subjectText} onChange={e=>setSearch({subjectText:e.target.value})} placeholder="Ej. acceso"/></label>
 <Filter label="Estado" value={criteria.status} options={statuses} change={value=>setSearch({status:value})}/>
 <Filter label="Prioridad" value={criteria.priority} options={["Baja","Media","Alta","Crítica"]} change={value=>setSearch({priority:value})}/>
 <Filter label="Categoría" value={criteria.category} options={["Acceso","Hardware","Software","Red","Otro"]} change={value=>setSearch({category:value})}/>
 <Filter label="Técnico asignado" value={criteria.technicianId} options={technicians} change={value=>setSearch({technicianId:value})} unassigned/>
 </div><div className="resultbar"><p role="status">{result.total} resultados · {Object.entries(criteria).filter(([key,value])=>!["page","pageSize"].includes(key)&&Boolean(value)).length} criterios activos</p><button className="secondary" onClick={()=>setCriteria(emptyCriteria())}>Limpiar búsqueda y filtros</button></div>
 <TicketTable rows={result.items} role={role} open={openDetail}/><nav className="pagination" aria-label="Paginación de solicitudes"><button className="secondary" disabled={result.page<=1||!result.total} onClick={()=>setCriteria(current=>({...current,page:result.page-1}))}>Anterior</button><span>{result.total?`Página ${result.page} de ${result.pageCount}`:"0 resultados"}</span><button className="secondary" disabled={!result.total||result.page>=result.pageCount} onClick={()=>setCriteria(current=>({...current,page:result.page+1}))}>Siguiente</button></nav></section>}
 {ready&&view==="Nueva solicitud"&&role!=="Técnico"&&<section className="card"><h3>Registrar una solicitud</h3><form className="form" onSubmit={create}><label className="field full">Asunto<input name="title" required minLength={5}/></label><label className="field full">Descripción<textarea name="description" required minLength={10} rows={5}/></label><label className="field">Solicitante<input name="requester" required defaultValue={role==="Colaborador"?context.userId:"Adriana Ramirez Bernal"} readOnly={role==="Colaborador"}/></label><Field name="category" label="Categoría" options={["Acceso","Hardware","Software","Red","Otro"]}/><Field name="impact" label="Impacto" options={["1|Bajo","2|Medio","3|Alto"]}/><Field name="urgency" label="Urgencia" options={["1|Baja","2|Media","3|Alta"]}/><div className="full"><button className="primary">Crear solicitud</button></div></form></section>}
 {view==="Evaluación"&&<section className="card"><h3>Comparación de estrategias de búsqueda</h3><p className="description">Evalúa 100, 1.000 y 10.000 solicitudes sintéticas en un conjunto independiente. Compara búsqueda por código y consulta completa, con 20 repeticiones por escenario.</p><button className="primary" disabled={busy} onClick={evaluate}>{busy?"Evaluando…":"Ejecutar evaluación"}</button><p role="status">{progress}</p>{benchmark&&<><div className="resultbar"><strong>Resultados medidos en este navegador</strong><div className="downloads"><button className="secondary" onClick={()=>download('ServiceBank-Adriana-resultados.json',JSON.stringify(benchmark,null,2),'application/json')}>Descargar JSON</button><button className="secondary" onClick={()=>download('ServiceBank-Adriana-resultados.csv',reportCSV(benchmark),'text/csv;charset=utf-8')}>Descargar CSV</button></div></div><p className="muted">Mediana en milisegundos por operación. El intervalo P10–P90 muestra la dispersión de las mediciones.</p><div className="tablewrap"><table><thead><tr><th>Solicitudes</th><th>Estrategia</th><th>Fase / escenario</th><th>Mediana (ms)</th><th>P10–P90 (ms)</th></tr></thead><tbody>{benchmark.measurements.map((m,i)=><tr key={i}><td>{m.datasetSize.toLocaleString('es-CO')}</td><td>{m.strategy}</td><td>{m.phase}<div className="muted">{m.scenario}</div></td><td>{m.medianMs.toFixed(6)}</td><td>{m.p10Ms.toFixed(6)}–{m.p90Ms.toFixed(6)}</td></tr>)}</tbody></table></div><h4>Alcance de las mediciones</h4><ul className="limitations">{benchmark.limitations.map(text=><li key={text}>{text}</li>)}</ul></>}</section>}
 </main></div>
 {selected&&<div className="overlay" role="dialog" aria-modal="true" aria-label={`Detalle ${selected.code}`} onMouseDown={e=>{if(e.target===e.currentTarget)closeDetail()}} onKeyDown={e=>{if(e.key==='Escape')closeDetail();if(e.key==='Tab'){const elements=detailRef.current?.querySelectorAll<HTMLElement>('button,input,select,textarea,a[href]');if(elements?.length){const first=elements[0],last=elements[elements.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}}><article className="detail" ref={detailRef}><div className="detailhead"><div><span className="code">{selected.code}</span><h2>{selected.title}</h2></div><button className="close" aria-label="Cerrar detalle" onClick={closeDetail}>×</button></div><p className="description">{selected.description}</p>
  <div className="facts"><Fact label="Categoría" value={selected.category}/><Fact label="Prioridad" value={selected.priority}/><Fact label="Estado" value={selected.status}/><Fact label="Solicitante" value={selected.requester}/><Fact label="Responsable" value={selected.assignee||"Sin asignar"}/><Fact label="Creación" value={selected.createdAt}/></div>
  {role!=="Colaborador"&&<div className="management"><label className="field">Estado<select value={selected.status} onChange={e=>changeStatus(selected,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label>{["Agente","Administrador"].includes(role)&&<label className="field">Responsable<select value={selected.assignee||""} onChange={e=>assign(selected,e.target.value)}><option value="" disabled>Seleccionar técnico</option>{technicians.map(t=><option key={t}>{t}</option>)}</select></label>}</div>}
  <div className="detailgrid"><section><h3>Comentarios</h3><form className="commentform" onSubmit={e=>addComment(e,selected)}><textarea aria-label="Comentario de seguimiento" name="comment" required minLength={3} placeholder="Agregar una observación..." rows={3}/><button className="primary">Agregar comentario</button></form><div className="timeline">{selected.comments.length?selected.comments.slice().reverse().map(c=><div className="timelineitem" key={c.id}><strong>{c.author}</strong><span>{c.date}</span><p>{c.text}</p></div>):<p className="empty">Todavía no hay comentarios.</p>}</div></section>
  <section><h3>Historial</h3><div className="timeline">{selected.events.slice().reverse().map(ev=><div className="timelineitem" key={ev.id}><strong>{ev.type}</strong><span>{ev.date}</span><p>{ev.detail}</p><small>{ev.actor}</small></div>)}</div></section></div>
 </article></div>}</>}

function Field({name,label,options}:{name:string;label:string;options:string[]}){return <label className="field">{label}<select name={name}>{options.map(o=>{const [v,l]=o.includes("|")?o.split("|"):[o,o];return <option value={v} key={v}>{l}</option>})}</select></label>}
function Filter({label,value,options,change,unassigned=false}:{label:string;value:string;options:string[];change:(value:string)=>void;unassigned?:boolean}){return <label className="field">{label}<select value={value} onChange={event=>change(event.target.value)}><option value="">Todos</option>{unassigned&&<option value="__unassigned">Sin asignar</option>}{options.map(option=><option key={option}>{option}</option>)}</select></label>}
function Fact({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function TicketTable({rows,role,open}:{rows:readonly Ticket[];role:string;open:(id:number)=>void}){return <div className="tablewrap"><table><thead><tr><th>Código</th><th>Solicitud</th><th>Prioridad</th><th>Estado</th><th>Responsable</th><th>Acción</th></tr></thead><tbody>{rows.map(t=><tr key={t.id}><td className="code">{t.code}</td><td><strong>{t.title}</strong><div className="muted">{t.requester} · {t.category}</div></td><td><span className={"pill "+t.priority.toLowerCase()}>{t.priority}</span></td><td>{t.status}</td><td>{t.assignee||"Sin asignar"}</td><td><button className="secondary" onClick={()=>open(t.id)}>{role==="Colaborador"?"Consultar":"Gestionar"}</button></td></tr>)}</tbody></table>{!rows.length&&<p className="empty">No se encontraron solicitudes.</p>}</div>}
