"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";

type Event={id:number;type:string;detail:string;actor:string;date:string};
type Comment={id:number;text:string;author:string;date:string};
type Ticket={id:number;code:string;title:string;description:string;category:string;priority:string;status:string;requester:string;assignee:string|null;createdAt:string;events:Event[];comments:Comment[]};
const now="30/08/2026, 6:00 p. m.";
const seed:Ticket[]=[
{id:1,code:"SB-DEMO-001",title:"Bloqueo de usuario en portal interno",description:"Un usuario de demostración no puede acceder al portal desde el inicio de su turno.",category:"Acceso",priority:"Alta",status:"En progreso",requester:"Usuario Demo 01",assignee:"Técnico Demo A",createdAt:now,events:[{id:1,type:"Creación",detail:"Solicitud demostrativa registrada con prioridad Alta",actor:"Usuario Demo 01",date:now},{id:2,type:"Asignación",detail:"Responsable asignado: Técnico Demo A",actor:"Agente de mesa",date:now}],comments:[]},
{id:2,code:"SB-DEMO-002",title:"Falla de impresión en oficina",description:"Una impresora del entorno de pruebas no responde y presenta documentos en cola.",category:"Hardware",priority:"Media",status:"Abierto",requester:"Usuario Demo 02",assignee:null,createdAt:now,events:[{id:1,type:"Creación",detail:"Solicitud demostrativa registrada con prioridad Media",actor:"Usuario Demo 02",date:now}],comments:[]},
{id:3,code:"SB-DEMO-003",title:"Actualización de cliente VPN",description:"Caso académico para actualizar el cliente seguro en equipos de demostración.",category:"Software",priority:"Baja",status:"Resuelto",requester:"Usuario Demo 03",assignee:"Técnico Demo B",createdAt:now,events:[{id:1,type:"Creación",detail:"Solicitud demostrativa registrada con prioridad Baja",actor:"Usuario Demo 03",date:now},{id:2,type:"Estado",detail:"Estado actualizado a Resuelto",actor:"Técnico Demo B",date:now}],comments:[{id:1,text:"Actualización de demostración completada y validada.",author:"Técnico Demo B",date:now}]},
{id:4,code:"SB-DEMO-004",title:"Intermitencia de red en sede de prueba",description:"Caso ficticio de pérdida de conectividad reportada en un entorno de demostración.",category:"Red",priority:"Crítica",status:"Cerrado",requester:"Usuario Demo 04",assignee:"Técnico Demo C",createdAt:now,events:[{id:1,type:"Creación",detail:"Solicitud demostrativa registrada con prioridad Crítica",actor:"Usuario Demo 04",date:now},{id:2,type:"Estado",detail:"Estado actualizado a Cerrado",actor:"Técnico Demo C",date:now}],comments:[]}
];
const technicians=["Técnico Demo A","Técnico Demo B","Técnico Demo C","Técnico Demo D"];
const statuses=["Abierto","En progreso","Resuelto","Cerrado"];
const stamp=()=>new Date().toLocaleString("es-CO");
const event=(type:string,detail:string,actor:string):Event=>({id:Date.now()+Math.random(),type,detail,actor,date:stamp()});

export default function Home(){
 const [tickets,setTickets]=useState<Ticket[]>(seed),[view,setView]=useState("Resumen"),[role,setRole]=useState("Agente"),[query,setQuery]=useState(""),[notice,setNotice]=useState(""),[selectedId,setSelectedId]=useState<number|null>(null);
 useEffect(()=>{const raw=localStorage.getItem("servicebank-tickets-v2");if(raw){try{setTickets(JSON.parse(raw))}catch{localStorage.removeItem("servicebank-tickets-v2")}}},[]);
 const save=(next:Ticket[])=>{setTickets(next);localStorage.setItem("servicebank-tickets-v2",JSON.stringify(next))};
 const selected=tickets.find(t=>t.id===selectedId)||null;
 const filtered=useMemo(()=>tickets.filter(t=>(t.code+t.title+t.requester).toLowerCase().includes(query.toLowerCase())),[tickets,query]);
 const counts=[tickets.filter(t=>["Abierto","En progreso"].includes(t.status)).length,tickets.filter(t=>t.priority==="Crítica"&&t.status!=="Cerrado").length,tickets.filter(t=>["Resuelto","Cerrado"].includes(t.status)).length];
 const actor=`Usuario demo (${role})`;
 function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f),impact=Number(d.get("impact")),urgency=Number(d.get("urgency")),score=impact+urgency,priority=score>=6?"Crítica":score>=5?"Alta":score>=3?"Media":"Baja",id=Date.now();const t:Ticket={id,code:`SB-${String(id).slice(-6)}`,title:String(d.get("title")),description:String(d.get("description")),category:String(d.get("category")),priority,status:"Abierto",requester:String(d.get("requester")),assignee:null,createdAt:stamp(),events:[event("Creación",`Solicitud registrada con prioridad ${priority}`,String(d.get("requester")))],comments:[]};save([t,...tickets]);f.reset();setNotice("Solicitud creada correctamente.");setView("Solicitudes")}
 function updateTicket(id:number,mutate:(t:Ticket)=>Ticket){save(tickets.map(t=>t.id===id?mutate(t):t))}
 function changeStatus(t:Ticket,status:string){if(role==="Colaborador")return;updateTicket(t.id,x=>({...x,status,events:[...x.events,event("Estado",`Estado actualizado de ${x.status} a ${status}`,actor)]}))}
 function assign(t:Ticket,assignee:string){if(!["Agente","Administrador"].includes(role))return;updateTicket(t.id,x=>({...x,assignee,events:[...x.events,event("Asignación",`Responsable asignado: ${assignee}`,actor)]}))}
 function addComment(e:FormEvent<HTMLFormElement>,t:Ticket){e.preventDefault();const f=e.currentTarget,text=String(new FormData(f).get("comment")).trim();if(!text)return;updateTicket(t.id,x=>({...x,comments:[...x.comments,{id:Date.now(),text,author:actor,date:stamp()}],events:[...x.events,event("Comentario","Se agregó una observación de seguimiento",actor)]}));f.reset()}
 const nav=["Resumen","Solicitudes","Nueva solicitud"];
 return <><header><div className="top"><div className="brand"><div className="logo">SB</div><div><h1>ServiceBank</h1><p>Mesa de servicio tecnológica</p></div></div><span className="academic">Prototipo académico</span><select aria-label="Perfil activo" className="role" value={role} onChange={e=>setRole(e.target.value)}>{["Colaborador","Agente","Técnico","Administrador"].map(x=><option key={x}>{x}</option>)}</select></div></header>
 <div className="layout"><aside><p className="navtitle">NAVEGACIÓN</p>{nav.map(x=><button className={"nav "+(view===x?"active":"")} key={x} onClick={()=>{setView(x);setNotice("");setSelectedId(null)}}>{x}</button>)}<div className="safe"><strong>Entorno de demostración</strong><br/>No contiene información real de Itaú ni autentica usuarios bancarios.</div></aside>
 <main className="content"><div className="eyebrow">OPERACIÓN TI</div><h2>{view}</h2><div className="sub">Vista activa como {role}. {role==="Colaborador"?"Puedes registrar, consultar y comentar solicitudes.":role==="Técnico"?"Puedes comentar y actualizar el estado de atención.":"Puedes asignar responsables y gestionar el ciclo de atención."}</div>{notice&&<div className="notice">{notice}</div>}
 {view==="Resumen"&&<><div className="cards">{[["Solicitudes activas",counts[0]],["Prioridad crítica",counts[1]],["Resueltas",counts[2]]].map(x=><section className="card" key={x[0]}><div className="sub">{x[0]}</div><div className="metric">{x[1]}</div></section>)}</div><section className="card section"><h3>Actividad reciente</h3><TicketTable rows={tickets.slice(0,5)} role={role} open={setSelectedId}/></section></>}
 {view==="Solicitudes"&&<section className="card"><div className="toolbar"><h3>Listado de solicitudes</h3><input aria-label="Buscar solicitudes" className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar código, asunto o solicitante"/></div><TicketTable rows={filtered} role={role} open={setSelectedId}/></section>}
 {view==="Nueva solicitud"&&<section className="card"><h3>Registrar una solicitud</h3><form className="form" onSubmit={create}><label className="field full">Asunto<input name="title" required minLength={5}/></label><label className="field full">Descripción<textarea name="description" required minLength={10} rows={5}/></label><label className="field">Solicitante<input name="requester" required defaultValue="Adriana Ramírez"/></label><Field name="category" label="Categoría" options={["Acceso","Hardware","Software","Red","Otro"]}/><Field name="impact" label="Impacto" options={["1|Bajo","2|Medio","3|Alto"]}/><Field name="urgency" label="Urgencia" options={["1|Baja","2|Media","3|Alta"]}/><div className="full"><button className="primary">Crear solicitud</button></div></form></section>}
 </main></div>
 {selected&&<div className="overlay" role="dialog" aria-modal="true" aria-label={`Detalle ${selected.code}`} onMouseDown={e=>{if(e.target===e.currentTarget)setSelectedId(null)}}><article className="detail"><div className="detailhead"><div><span className="code">{selected.code}</span><h2>{selected.title}</h2></div><button className="close" aria-label="Cerrar detalle" onClick={()=>setSelectedId(null)}>×</button></div><p className="description">{selected.description}</p>
  <div className="facts"><Fact label="Categoría" value={selected.category}/><Fact label="Prioridad" value={selected.priority}/><Fact label="Estado" value={selected.status}/><Fact label="Solicitante" value={selected.requester}/><Fact label="Responsable" value={selected.assignee||"Sin asignar"}/><Fact label="Creación" value={selected.createdAt}/></div>
  {role!=="Colaborador"&&<div className="management"><label className="field">Estado<select value={selected.status} onChange={e=>changeStatus(selected,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label>{["Agente","Administrador"].includes(role)&&<label className="field">Responsable<select value={selected.assignee||""} onChange={e=>assign(selected,e.target.value)}><option value="" disabled>Seleccionar técnico</option>{technicians.map(t=><option key={t}>{t}</option>)}</select></label>}</div>}
  <div className="detailgrid"><section><h3>Comentarios</h3><form className="commentform" onSubmit={e=>addComment(e,selected)}><textarea aria-label="Comentario de seguimiento" name="comment" required minLength={3} placeholder="Agregar una observación..." rows={3}/><button className="primary">Agregar comentario</button></form><div className="timeline">{selected.comments.length?selected.comments.slice().reverse().map(c=><div className="timelineitem" key={c.id}><strong>{c.author}</strong><span>{c.date}</span><p>{c.text}</p></div>):<p className="empty">Todavía no hay comentarios.</p>}</div></section>
  <section><h3>Historial</h3><div className="timeline">{selected.events.slice().reverse().map(ev=><div className="timelineitem" key={ev.id}><strong>{ev.type}</strong><span>{ev.date}</span><p>{ev.detail}</p><small>{ev.actor}</small></div>)}</div></section></div>
 </article></div>}</>}

function Field({name,label,options}:{name:string;label:string;options:string[]}){return <label className="field">{label}<select name={name}>{options.map(o=>{const [v,l]=o.includes("|")?o.split("|"):[o,o];return <option value={v} key={v}>{l}</option>})}</select></label>}
function Fact({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function TicketTable({rows,role,open}:{rows:Ticket[];role:string;open:(id:number)=>void}){return <div className="tablewrap"><table><thead><tr><th>Código</th><th>Solicitud</th><th>Prioridad</th><th>Estado</th><th>Responsable</th><th>Acción</th></tr></thead><tbody>{rows.map(t=><tr key={t.id}><td className="code">{t.code}</td><td><strong>{t.title}</strong><div className="muted">{t.requester} · {t.category}</div></td><td><span className={"pill "+t.priority.toLowerCase()}>{t.priority}</span></td><td>{t.status}</td><td>{t.assignee||"Sin asignar"}</td><td><button className="secondary" onClick={()=>open(t.id)}>{role==="Colaborador"?"Consultar":"Gestionar"}</button></td></tr>)}</tbody></table>{!rows.length&&<p className="empty">No se encontraron solicitudes.</p>}</div>}
